# Generated by Django 5.0 on 2024-02-18 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTrip', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='viajesros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('apellido', models.CharField(max_length=250)),
                ('edad', models.IntegerField()),
            ],
        ),
    ]
