# Generated by Django 5.0 on 2024-02-19 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppTrip', '0002_viajesros'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='fecha_publicacion',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='usuario',
        ),
    ]
