# Generated by Django 5.0 on 2024-02-19 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppTrip', '0006_alter_avatar_options_imagenes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='imagenes',
        ),
    ]
